parameters:
    bukatov_api_token.security.authentication.get.listener.class: Bukatov\ApiTokenBundle\Security\Firewall\GetApiTokenListener
    bukatov_api_token.security.authentication.get.provider.class: Bukatov\ApiTokenBundle\Security\Authentication\Provider\GetApiTokenProvider

    bukatov_api_token.security.authentication.listener.class: Bukatov\ApiTokenBundle\Security\Firewall\ApiTokenListener
    bukatov_api_token.doctrine.orm.security.provider.class: Bukatov\ApiTokenBundle\Security\Core\User\EntityApiTokenUserProvider

    bukatov_api_token.security.authentication.token.provider.class: Bukatov\ApiTokenBundle\Security\Authentication\Provider\ApiTokenProvider

    bukatov_api_token.fetcher.headers.class: Bukatov\ApiTokenBundle\ParameterFetcher\HeadersParameterFetcher
    bukatov_api_token.fetcher.query_string.class: Bukatov\ApiTokenBundle\ParameterFetcher\QueryStringParameterFetcher
    bukatov_api_token.fetcher.post_body.class: Bukatov\ApiTokenBundle\ParameterFetcher\PostBodyParameterFetcher
    bukatov_api_token.fetcher.json_post_body.class: Bukatov\ApiTokenBundle\ParameterFetcher\JsonPostBodyParameterFetcher

    bukatov_api_token.security.authentication.manager.class: Bukatov\ApiTokenBundle\Security\Core\AuthenticationManager

    bukatov_api_token.provider.factory.class: Bukatov\ApiTokenBundle\Security\Authentication\Provider\ProviderFactory
    bukatov_api_token.user.provider.factory.class: Bukatov\ApiTokenBundle\Security\Core\User\UserProviderFactory

services:
    bukatov_api_token.security.authentication.get.listener:
        class: %bukatov_api_token.security.authentication.get.listener.class%
        arguments: ["@security.token_storage", "@security.authentication.manager", "", "", "", ""]

    bukatov_api_token.security.authentication.get.provider:
        class: %bukatov_api_token.security.authentication.get.provider.class%
        arguments: ["", @security.user_checker, @security.encoder_factory, %security.authentication.hide_user_not_found%]

    bukatov_api_token.security.authentication.listener:
        class: %bukatov_api_token.security.authentication.listener.class%
        arguments: ["@security.token_storage", "@security.authentication.manager", "", ""]

    bukatov_api_token.doctrine.orm.security.provider:
        class: %bukatov_api_token.doctrine.orm.security.provider.class%
        arguments: ["@doctrine", "", ""]

    bukatov_api_token.security.authentication.token.provider:
        class: %bukatov_api_token.security.authentication.token.provider.class%
        arguments: [""]

    bukatov_api_token.fetcher.headers:
        class: %bukatov_api_token.fetcher.headers.class%
        public: false

    bukatov_api_token.fetcher.query_string:
        class: %bukatov_api_token.fetcher.query_string.class%
        public: false

    bukatov_api_token.fetcher.post_body:
        class: %bukatov_api_token.fetcher.post_body.class%
        public: false

    bukatov_api_token.fetcher.json_post_body:
        class: %bukatov_api_token.fetcher.json_post_body.class%
        public: false

    bukatov_api_token.security.authentication.manager:
        class: %bukatov_api_token.security.authentication.manager.class%
        parent: security.authentication.manager
        public: true
        calls:
            - [setTokenStorage, [@security.token_storage]]

    bukatov_api_token.provider.factory:
        class: %bukatov_api_token.provider.factory.class%
        arguments:
            - @security.user_checker
            - @security.encoder_factory
            - @bukatov_api_token.user.provider.factory
            - %security.authentication.hide_user_not_found%
            - %bukatov_api_token.token.lifetime%
            - %bukatov_api_token.token.idle_time%

    bukatov_api_token.user.provider.factory:
        class: %bukatov_api_token.user.provider.factory.class%
        arguments: ["@doctrine", %bukatov_api_token.provider.user_entity_class%]