parameters:
    bukatov_api_token.security.authentication.listener.login.class: Bukatov\ApiTokenBundle\Security\Firewall\LoginListener
    bukatov_api_token.security.authentication.provider.login.class: Bukatov\ApiTokenBundle\Security\Authentication\Provider\LoginProvider

    bukatov_api_token.security.authentication.listener.secure.class: Bukatov\ApiTokenBundle\Security\Firewall\SecureListener
    bukatov_api_token.security.authentication.provider.secure.class: Bukatov\ApiTokenBundle\Security\Authentication\Provider\SecureProvider

    bukatov_api_token.request_param_fetcher.headers.class: Bukatov\ApiTokenBundle\RequestParamFetcher\HeadersRequestParamFetcher
    bukatov_api_token.request_param_fetcher.query_string.class: Bukatov\ApiTokenBundle\RequestParamFetcher\QueryStringParamFetcher
    bukatov_api_token.request_param_fetcher.post_body.class: Bukatov\ApiTokenBundle\RequestParamFetcher\PostBodyRequestParamFetcher
    bukatov_api_token.request_param_fetcher.json_post_body.class: Bukatov\ApiTokenBundle\RequestParamFetcher\JsonPostBodyRequestParamFetcher

    bukatov_api_token.security.authentication.manager.class: Bukatov\ApiTokenBundle\Security\Core\AuthenticationManager

    bukatov_api_token.storage.sql.class: Bukatov\ApiTokenBundle\ApiToken\Storage\SqlApiTokenStorage
    bukatov_api_token.storage.sql.table_name: api_token

    bukatov_api_token.storage.apc.class: Bukatov\ApiTokenBundle\ApiToken\Storage\ApcApiTokenStorage
    bukatov_api_token.manager.class: Bukatov\ApiTokenBundle\ApiToken\Manager\ApiTokenManager

services:
    bukatov_api_token.security.authentication.listener.login:
        class: %bukatov_api_token.security.authentication.listener.login.class%
        arguments: [@security.token_storage, @security.authentication.manager, "", "", "", ""]

    bukatov_api_token.security.authentication.provider.login:
        class: %bukatov_api_token.security.authentication.provider.login.class%
        arguments: [@bukatov_api_token.manager, "", @security.user_checker, @security.encoder_factory, %security.authentication.hide_user_not_found%]
        calls:
            - [setTokenAbsoluteLifetime, [%bukatov_api_token.lifetime.absolute%]]
            - [setTokenInactiveLifetime, [%bukatov_api_token.lifetime.inactive%]]

    bukatov_api_token.security.authentication.listener.secure:
        class: %bukatov_api_token.security.authentication.listener.secure.class%
        arguments: ["@security.token_storage", "@security.authentication.manager", "", ""]

    bukatov_api_token.security.authentication.provider.secure:
        class: %bukatov_api_token.security.authentication.provider.secure.class%
        arguments: ["@bukatov_api_token.manager", ""]
        calls:
            - [setTokenInactiveLifetime, [%bukatov_api_token.lifetime.inactive%]]

    bukatov_api_token.request_param_fetcher.headers:
        class: %bukatov_api_token.request_param_fetcher.headers.class%
        public: false

    bukatov_api_token.request_param_fetcher.query_string:
        class: %bukatov_api_token.request_param_fetcher.query_string.class%
        public: false

    bukatov_api_token.request_param_fetcher.post_body:
        class: %bukatov_api_token.request_param_fetcher.post_body.class%
        public: false

    bukatov_api_token.request_param_fetcher.json_post_body:
        class: %bukatov_api_token.request_param_fetcher.json_post_body.class%
        public: false

    bukatov_api_token.security.authentication.manager:
        class: %bukatov_api_token.security.authentication.manager.class%
        parent: security.authentication.manager
        public: true
        calls:
            - [setTokenStorage, [@security.token_storage]]
            - [setEventDispatcher, [@event_dispatcher]]

    bukatov_api_token.manager:
        class: %bukatov_api_token.manager.class%
        arguments: [""]

    bukatov_api_token.storage.sql:
        class: %bukatov_api_token.storage.sql.class%
        arguments: [@database_connection, %bukatov_api_token.storage.sql.table_name%]

    bukatov_api_token.storage.apc:
        class: %bukatov_api_token.storage.apc.class%